[package]
name = "maturin-nix"
version = "0.1.0"
authors = ["Christopher Chalmers <c.chalmers@me.com>"]
edition = "2018"

exclude = [
  "examples/*",
]

[dependencies]
maturin = "1.5.0"
structopt = "0.3"
ansi_term = "0.12"
ignore = "0.4.22"
cargo_metadata = "0.18.1"
